### ISSUE TITLE
Infinite recursivity when using empty <relativePath>

### ISSUE THREAD

**Issue by jflecomte** [payara/ecosystem-support#12]
If a pom has a parent defined with an empty <relativePath>, the method PropertyResolver.getPropertyFromPom will recurse forever.

Example of such parent declaration:
```
    <parent>
        <groupId>org.apache</groupId>
        <artifactId>apache</artifactId>
        <version>23</version>
        <relativePath></relativePath>
    </parent>
```

Stack trace generated is:

```
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
        at java.io.InputStream.<init>(InputStream.java:45)
        at java.io.FileInputStream.<init>(FileInputStream.java:123)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.readMavenProject(PropertyResolver.java:181)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:148)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:173)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:173)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:173)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:173)
        at fish.payara.maven.extensions.regex.activator.PropertyResolver.getPropertyFromPom(PropertyResolver.java:173)
```

**Comment by fturizo** [comment]
This issue was fixed by the linked PR, closing it.
