### ISSUE TITLE
Bug Report:  Deploying a WAR file on Payara 5.201 [VS Code]

### ISSUE THREAD

**Issue by lewalkingdad** [payara/ecosystem-support#32]
# Description #

I'm trying to deploy a war file on Payara 5.201 via VSCode, just like the gif in the repo. But every time I'm trying regardless if it's a simple run or a debug, it fails. An error tooltip shows up saying `Application deployment failed:` and an empty description.

Looking at my system logs, I can see there is a null pointer every time I tried to deploy:

```
[#|2021-07-27T02:11:21.495+0000|SEVERE|Payara 5.201|javax.enterprise.system.core|_ThreadID=234;_ThreadName=admin-thread-pool::admin-listener(2);_TimeMillis=1627351881495;_LevelValue=1000;_MessageID=NCLS-CORE-00003;|
  Exception while running a command
java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
        at org.glassfish.admin.payload.ZipPayloadImpl$Extra.<init>(ZipPayloadImpl.java:348)
        at org.glassfish.admin.payload.ZipPayloadImpl$Extra.<init>(ZipPayloadImpl.java:339)
        at org.glassfish.admin.payload.ZipPayloadImpl$Inbound$1.next(ZipPayloadImpl.java:287)
        at org.glassfish.admin.payload.ZipPayloadImpl$Inbound$1.next(ZipPayloadImpl.java:271)
        at org.glassfish.admin.payload.PayloadFilesManager.processPartsExtended(PayloadFilesManager.java:570)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$UploadedFilesManager.extractFiles(CommandRunnerImpl.java:2107)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$UploadedFilesManager.<init>(CommandRunnerImpl.java:2078)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$UploadedFilesManager.<init>(CommandRunnerImpl.java:2057)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1186)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1878)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1754)
        at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
        at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
        at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
|#]
```

## Expected Outcome ##

The war file is deployed successfully.

## Current Outcome ##

The war file is not deployed.

## Environment ##

- **Ecosystem Plugin/Tool**: VSCode 
- **Operating System**: Linux (NixOS 21.05)
- **VS Code** : 
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.50
```

**Comment by jGauravGupta** [comment]
Hi @damien-biasotto , 

May you also share the VSCode logs? Goto Help > Toggle Developer tools > console tab to view it.

**Comment by lewalkingdad** [comment]
@jGauravGupta There you go: 

It looks like it is relying on `JAVA_HOME` env variable, and does not fallback on the settings `java.home`.

My settings:
```
{
    "explorer.confirmDragAndDrop": false,
    "[purescript]": {
        "editor.defaultFormatter": "nwolverson.ide-purescript"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-1.8",
        "path": "/home/damien/.jdks/openjdk8/lib/openjdk",
      },
      {
        "name": "JavaSE-11",
        "path": "/home/damien/.jdks/openjdk11/lib/openjdk",
      },
      {
        "name": "JavaSE-16",
        "path": "/home/damien/.jdks/openjdk16/lib/openjdk",
        "default": true
      },
    ],
    "java.home": "/home/damien/.jdks/openjdk11/lib/openjdk",
    "files.exclude": {
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
    },
    "maven.executable.options": "-o -DskipTests"
}
```

The logs:

```
workbench.desktop.main.js:741 Couldn't locate java in $JAVA_HOME or $PATH
onDidChangeNotification @ workbench.desktop.main.js:741
(anonymous) @ workbench.desktop.main.js:741
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:741
notify @ workbench.desktop.main.js:1872
(anonymous) @ workbench.desktop.main.js:1825
_showMessage @ workbench.desktop.main.js:1825
$showMessage @ workbench.desktop.main.js:1825
_doInvokeHandler @ workbench.desktop.main.js:1832
_invokeHandler @ workbench.desktop.main.js:1832
_receiveRequest @ workbench.desktop.main.js:1832
_receiveOneMessage @ workbench.desktop.main.js:1832
(anonymous) @ workbench.desktop.main.js:1832
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
D @ workbench.desktop.main.js:2938
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:62 [Extension Host] Application activemq-rar contains no web modules.
workbench.desktop.main.js:741 Application deployment failed:
onDidChangeNotification @ workbench.desktop.main.js:741
(anonymous) @ workbench.desktop.main.js:741
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:741
notify @ workbench.desktop.main.js:1872
(anonymous) @ workbench.desktop.main.js:1825
_showMessage @ workbench.desktop.main.js:1825
$showMessage @ workbench.desktop.main.js:1825
_doInvokeHandler @ workbench.desktop.main.js:1832
_invokeHandler @ workbench.desktop.main.js:1832
_receiveRequest @ workbench.desktop.main.js:1832
_receiveOneMessage @ workbench.desktop.main.js:1832
(anonymous) @ workbench.desktop.main.js:1832
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
D @ workbench.desktop.main.js:2938
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/507ce72a4466fbb27b715c3722558bb15afa9f48/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```

**Comment by jGauravGupta** [comment]
Hi @damien-biasotto ,

`java.home` path from settings having greater priority over `JDK_HOME` and `JAVA_HOME` env.

https://github.com/payara/ecosystem-vscode-plugin/blob/master/src/main/fish/payara/server/start/JDKVersion.ts#L247-L264

**Comment by OndroMih** [comment]
Hi, @damien-biasotto ,
is this resolved by setting the correct Java path?

**Comment by baudev** [comment]
Same bug here... 
Nothing is logged into the console Dev tools (except "`application deployment failed`")

**Comment by lewalkingdad** [comment]
@jGauravGupta @OndroMih Sorry for the late reply, sadly, I can no longer test it anymore (changed job and tech stack). I'll close the issue for you, as I believe it should work (it is very likely the `java.home` path was not correct in my config).
