### ISSUE TITLE
Exception in IntelliJ Plugin Payara Platfrom Tools 1.4.0

### ISSUE THREAD

**Issue by StevenHachel** [payara/ecosystem-support#49]
I got an error message when using the plugin.

This error only appears randomly. Not reproducible for me.

```
com.intellij.diagnostic.PluginException: ID 'fish.payara.micro.actions.MicroStartAction' is already taken by action 'Start Micro (Start Payara Micro)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction)  (Plugin: Payara Micro Community Tools). Action 'Start Micro (Start Payara Micro)' (class com.intellij.openapi.actionSystem.ActionStub) cannot use the same ID fish.payara.intellij [Plugin: fish.payara.intellij]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1330)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1264)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:718)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:688)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:485)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:141)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.getInstanceEx(ActionManagerEx.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.lambda$doWithLazyActionManager$1(ActionManagerEx.java:110)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Environment ##

- **Ecosystem Plugin/Tool**:  Intellij IDEA 2022.1.3, Plugin Payara Platfrom Tools 1.4.0
- **Operating System**: Windows 10

**Comment by StevenHachel** [comment]
> I got an error message when using the plugin.
> 
> This error only appears randomly. Not reproducible for me.
> 
> ```
> com.intellij.diagnostic.PluginException: ID 'fish.payara.micro.actions.MicroStartAction' is already taken by action 'Start Micro (Start Payara Micro)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction)  (Plugin: Payara Micro Community Tools). Action 'Start Micro (Start Payara Micro)' (class com.intellij.openapi.actionSystem.ActionStub) cannot use the same ID fish.payara.intellij [Plugin: fish.payara.intellij]
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1330)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1264)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:718)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:688)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:485)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:141)
> 	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
> 	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
> 	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
> 	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
> 	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.getInstanceEx(ActionManagerEx.java:20)
> 	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.lambda$doWithLazyActionManager$1(ActionManagerEx.java:110)
> 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ```
> 
> ## Environment
> * **Ecosystem Plugin/Tool**:  Intellij IDEA 2022.1.3, Plugin Payara Platfrom Tools 1.4.0
> * **Operating System**: Windows 10

Doesn't anyone feel responsible for this?

**Comment by JamesHillyard** [comment]
Hi @StevenHachel,

Thank you for following up with this, you stated this error isn't reproducible for you, could you please explain what you were doing when this error occurred so I can attempt to reproduce it myself.

The stack trace would imply this error occurs when starting Payara Micro via the `Start Micro` action, however I was unable to reproduce this error when doing this.

Thank you for your patience,
James

**Comment by StevenHachel** [comment]
Hello James,

as soon as IntelliJ starts, this error appears from the plugin.
A Payara 5 server is installed and not a Payara Micro.
Is that the reason?

Starting and debugging the Payara server works with it.


Many greetings
steven

Edit: I installed "Payara Micro Community Tools" and "Payara Platform Tools" in parallel.
The latter, which I am currently using, does not cause any problems when starting IntelliJ.

**Comment by JamesHillyard** [comment]
Hi Steven,

Having Payara Server installed and not Payara Micro shouldn't cause an issue within the IntelliJ Plugin. I installed both "Payara Micro Community Tools" and "Payara Platform Tools" to IntelliJ, however there is no error when starting IntelliJ.

What OS are you using? Are you using IntelliJ Ultimate? Please review and compare my environment below to yours as this may help me reproduce this issue.

**_Environment:_**
Windows 10 Pro
Zulu JDK 1.8.0_322
IntelliJ IDEA Ultimate 2022.1.4

Thanks,
James

**Comment by StevenHachel** [comment]
Hello :)

**Environment:**
IntelliJ IDEA 2022.1.4 (Ultimate Edition)
Build #IU-221.6008.13, built on July 19, 2022

Runtime version: 11.0.15+10-b2043.56 amd64 (Eclipse Temurin)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    org.jetbrains.intellij.scripting-javascript (1.0)
    org.jetbrains.kotlin (221-1.7.10-release-333-IJ5591.52)
    com.intellij.guice (221.6008.13)
    com.failfast (2.0.4)
    com.intellij.jsf (221.6008.13)
    Weblogic (221.6008.13)
    fish.payara.intellij (1.4.0)
    com.haulmont.jpab (2022.3.3-221)

Kotlin: 221-1.7.10-release-333-IJ5591.52

Steven

**Comment by JamesHillyard** [comment]
Hi Steven,

Thank you for sharing those details, I was able to consistently reproduce this error after installing both the Payara Platform Tools and Payara Micro Community Tools plugin and importantly **restarting the IDE with them both enabled**. It would therefore appear these two plugins are not compatible together in some way.

I have therefore raised an internal issue with the ID `FISH-6452` to address this bug. We always encourage you to contribute, so if you wish you can submit a PR with a fix and we will gladly review it. Otherwise, we will pick up the issue at some point in the future.

Thanks,
James

**Comment by JamesHillyard** [comment]
Hi @StevenHachel,

I would just like to provide an update on this, 
**Payara Platform Tools** - Contains both Payara Server and Payara Micro tools _(Only available on IntelliJ Ultimate)_
**Payara Micro Community Tools** - Contains only Payara Micro tools _(Available on IntelliJ Community)_

Therefore there is no need to have both plugins installed, as you are an IntelliJ Ultimate user you should remove Payara Micro Community Tools and just use Payara Platform Tools as that will contain all the tools you expect.

I am currently improving the ecosystem documentation, and so this will be clearer in the future.

Thanks,
James

**Comment by JamesHillyard** [comment]
I have closed the internal issue `FISH-6452` and raised the internal issue `SERV-819` to document this sufficiently.

**Comment by JamesHillyard** [comment]
`SERV-819` has been completed and the revamped documentation will be available soon.
