### ISSUE TITLE
Bug Report: Payara tools are not working on eclipse running on java 11 / FISH-6560 FISH-6561

### ISSUE THREAD

**Issue by gdiazs** [payara/ecosystem-support#51]
**OS**: macOS 12.4, M1 Chip
**JDK**  Temurin jdk-11.0.15+10 aarch64

**eclipse** (any latest version from official page)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112

logs:

```
!ENTRY org.eclipse.payara.tools 4 0 2022-08-01 17:35:22.625
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.payara.tools [1761]
  Unresolved requirement: Require-Bundle: com.sun.jna.platform; bundle-version="[4.5.1,5.0.0)"
    -> Bundle-SymbolicName: com.sun.jna.platform; bundle-version="4.5.1.v20190425-1842"
       com.sun.jna.platform [1760]
         Unresolved requirement: Import-Package: com.sun.jna; version="[4.5.1,4.6.0)"
           -> Export-Package: com.sun.jna; bundle-symbolic-name="com.sun.jna"; bundle-version="4.5.1.v20210503-0343"; version="4.5.1"
              com.sun.jna [1759]
                Unresolved requirement: Require-Capability: osgi.native; native.paths.8:List<String>="com/sun/jna/sunos-sparcv9/libjnidispatch.so"; native.paths.17:List<String>="com/sun/jna/linux-armel/libjnidispatch.so"; native.paths.7:List<String>="com/sun/jna/sunos-sparc/libjnidispatch.so"; native.paths.16:List<String>="com/sun/jna/linux-arm/libjnidispatch.so"; native.paths.19:List<String>="com/sun/jna/linux-ia64/libjnidispatch.so"; native.paths.9:List<String>="com/sun/jna/aix-ppc/libjnidispatch.a"; native.paths.18:List<String>="com/sun/jna/linux-aarch64/libjnidispatch.so"; native.paths.13:List<String>="com/sun/jna/linux-ppc64le/libjnidispatch.so"; native.paths.12:List<String>="com/sun/jna/linux-ppc64/libjnidispatch.so"; native.paths.15:List<String>="com/sun/jna/linux-x86-64/libjnidispatch.so"; native.paths.14:List<String>="com/sun/jna/linux-x86/libjnidispatch.so"; native.paths.11:List<String>="com/sun/jna/linux-ppc/libjnidispatch.so"; native.paths.10:List<String>="com/sun/jna/aix-ppc64/libjnidispatch.a"; native.paths.27:List<String>="com/sun/jna/darwin/libjnidispatch.jnilib"; native.paths.24:List<String>="com/sun/jna/freebsd-x86-64/libjnidispatch.so"; native.paths.23:List<String>="com/sun/jna/freebsd-x86/libjnidispatch.so"; native.paths.26:List<String>="com/sun/jna/openbsd-x86-64/libjnidispatch.so"; native.paths.25:List<String>="com/sun/jna/openbsd-x86/libjnidispatch.so"; native.paths.20:List<String>="com/sun/jna/linux-sparcv9/libjnidispatch.so"; native.paths.22:List<String>="com/sun/jna/linux-s390x/libjnidispatch.so"; native.paths.21:List<String>="com/sun/jna/linux-mips64el/libjnidispatch.so"; native.paths.0:List<String>="com/sun/jna/win32-x86/jnidispatch.dll"; native.paths.2:List<String>="com/sun/jna/win32-x86/jnidispatch.dll"; native.paths.1:List<String>="com/sun/jna/win32-x86-64/jnidispatch.dll"; native.paths.4:List<String>="com/sun/jna/w32ce-arm/jnidispatch.dll"; native.paths.3:List<String>="com/sun/jna/win32-x86-64/jnidispatch.dll"; native.paths.6:List<String>="com/sun/jna/sunos-x86-64/libjnidispatch.so"; native.paths.5:List<String>="com/sun/jna/sunos-x86/libjnidispatch.so"; filter:="(|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win)(osgi.native.processor~=x86))(&(osgi.native.osname~=win)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=wince)(osgi.native.processor~=arm))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparc))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=armel))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ia64))(&(osgi.native.osname~=linux)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=linux)(osgi.native.processor~=mips64el))(&(osgi.native.osname~=linux)(osgi.native.processor~=S390x))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(|(osgi.native.processor~=x86)(osgi.native.processor~=x86-64)(osgi.native.processor~=ppc))))"
  Unresolved requirement: Require-Bundle: com.sun.jna; bundle-version="[4.5.1,5.0.0)"
    -> Bundle-SymbolicName: com.sun.jna; bundle-version="4.5.1.v20210503-0343"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.payara.tools.ui 4 0 2022-08-01 17:35:22.628
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.payara.tools.ui [1763]
  Unresolved requirement: Require-Bundle: org.eclipse.payara.tools; bundle-version="[1.4.2,2.0.0)"
    -> Bundle-SymbolicName: org.eclipse.payara.tools; bundle-version="1.4.2.202201202255"; singleton:="true"
       org.eclipse.payara.tools [1761]
         Unresolved requirement: Require-Bundle: com.sun.jna.platform; bundle-version="[4.5.1,5.0.0)"
           -> Bundle-SymbolicName: com.sun.jna.platform; bundle-version="4.5.1.v20190425-1842"
              com.sun.jna.platform [1760]
                Unresolved requirement: Import-Package: com.sun.jna; version="[4.5.1,4.6.0)"
                  -> Export-Package: com.sun.jna; bundle-symbolic-name="com.sun.jna"; bundle-version="4.5.1.v20210503-0343"; version="4.5.1"
                     com.sun.jna [1759]
                       Unresolved requirement: Require-Capability: osgi.native; native.paths.8:List<String>="com/sun/jna/sunos-sparcv9/libjnidispatch.so"; native.paths.17:List<String>="com/sun/jna/linux-armel/libjnidispatch.so"; native.paths.7:List<String>="com/sun/jna/sunos-sparc/libjnidispatch.so"; native.paths.16:List<String>="com/sun/jna/linux-arm/libjnidispatch.so"; native.paths.19:List<String>="com/sun/jna/linux-ia64/libjnidispatch.so"; native.paths.9:List<String>="com/sun/jna/aix-ppc/libjnidispatch.a"; native.paths.18:List<String>="com/sun/jna/linux-aarch64/libjnidispatch.so"; native.paths.13:List<String>="com/sun/jna/linux-ppc64le/libjnidispatch.so"; native.paths.12:List<String>="com/sun/jna/linux-ppc64/libjnidispatch.so"; native.paths.15:List<String>="com/sun/jna/linux-x86-64/libjnidispatch.so"; native.paths.14:List<String>="com/sun/jna/linux-x86/libjnidispatch.so"; native.paths.11:List<String>="com/sun/jna/linux-ppc/libjnidispatch.so"; native.paths.10:List<String>="com/sun/jna/aix-ppc64/libjnidispatch.a"; native.paths.27:List<String>="com/sun/jna/darwin/libjnidispatch.jnilib"; native.paths.24:List<String>="com/sun/jna/freebsd-x86-64/libjnidispatch.so"; native.paths.23:List<String>="com/sun/jna/freebsd-x86/libjnidispatch.so"; native.paths.26:List<String>="com/sun/jna/openbsd-x86-64/libjnidispatch.so"; native.paths.25:List<String>="com/sun/jna/openbsd-x86/libjnidispatch.so"; native.paths.20:List<String>="com/sun/jna/linux-sparcv9/libjnidispatch.so"; native.paths.22:List<String>="com/sun/jna/linux-s390x/libjnidispatch.so"; native.paths.21:List<String>="com/sun/jna/linux-mips64el/libjnidispatch.so"; native.paths.0:List<String>="com/sun/jna/win32-x86/jnidispatch.dll"; native.paths.2:List<String>="com/sun/jna/win32-x86/jnidispatch.dll"; native.paths.1:List<String>="com/sun/jna/win32-x86-64/jnidispatch.dll"; native.paths.4:List<String>="com/sun/jna/w32ce-arm/jnidispatch.dll"; native.paths.3:List<String>="com/sun/jna/win32-x86-64/jnidispatch.dll"; native.paths.6:List<String>="com/sun/jna/sunos-x86-64/libjnidispatch.so"; native.paths.5:List<String>="com/sun/jna/sunos-x86/libjnidispatch.so"; filter:="(|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win)(osgi.native.processor~=x86))(&(osgi.native.osname~=win)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=wince)(osgi.native.processor~=arm))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparc))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=armel))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ia64))(&(osgi.native.osname~=linux)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=linux)(osgi.native.processor~=mips64el))(&(osgi.native.osname~=linux)(osgi.native.processor~=S390x))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(|(osgi.native.processor~=x86)(osgi.native.processor~=x86-64)(osgi.native.processor~=ppc))))"
         Unresolved requirement: Require-Bundle: com.sun.jna; bundle-version="[4.5.1,5.0.0)"
           -> Bundle-SymbolicName: com.sun.jna; bundle-version="4.5.1.v20210503-0343"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.jface 2 0 2022-08-01 17:35:30.800
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2022-08-01 17:35:30.800
!MESSAGE A conflict occurred for COMMAND+SHIFT+T:
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5481f204,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@171b0d3,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2022-08-01 17:35:30.800
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@63d43a5,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@55159007,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
```

<img width="775" alt="Screen Shot 2022-08-01 at 17 41 33" src="https://user-images.githubusercontent.com/2397243/182263025-e57d915f-105f-4a84-92d0-7b8ebbf96e99.png">

<img width="676" alt="Screen Shot 2022-08-01 at 17 41 50" src="https://user-images.githubusercontent.com/2397243/182263030-600747d9-0001-488a-a43c-e37ea03e3bbe.png">

**Comment by JamesHillyard** [comment]
Hi @gdiazs,

This issue has previously been brought to our attention regarding the Eclipse Plugin and Apple M1 hardware specifically. 

Apple M1 devices currently aren't supported, as unfortunately at this time we do not have the resources to test or reproduce bugs on Apple M1 hardware.

If there is a large desire from the community to have Apple M1 hardware support on Payara and the Payara Ecosystem, we may re-review this. Alternatively if you wish you can submit a PR with a fix, we always encourage you to contribute!

Best Regards,
James

**Comment by gdiazs** [comment]
@JamesHillyard thanks for answering. 
It's a shame M1 is not under support yet, it eventually will I guess...
 I'll try to see if there is something I can do if so, I'll come back with a PR, in the mean time will try to compile the plugin on the M1 and see what's happen `https://github.com/payara/ecosystem-eclipse-plugin`  
 
 To me it has to do with this: `osgi.native` but no idea, haven't work on eclipse plugins before so no idea how to start, thanks anyways.

**Comment by JamesHillyard** [comment]
Hi @gdiazs,

As identified by mwnorman on the [Payara forum - Eclipse Tools on M1](https://forum.payara.fish/t/eclipse-payara-tools-on-apple-silicon/197) Payara Eclipse Tools uses Sapphire XML Support which brings in the old JNA that does not work on M1 Macs. If you wish to submit a PR this may be a good place to start.

I have recently rewritten the build instructions for the Eclipse Plugin, however they haven't been published yet, so if you are unable to build the project I will happily provide the updated build instructions.

Thank you for your understanding,
James

**Comment by gdiazs** [comment]
Hello, Yes it's exactly what mwnorman said. I managed to run a build and got this: 
[out.log](https://github.com/payara/ecosystem-support/files/9256278/out.log)

Sorry for my ignorance, I did a quick review on the way the build is done I'm not familiar with Corundum which I guess is for automate the build and  release process. 

Regarding Corundum I couldn't find documentation googling. Is there something I can use as guidece so I can understand how the libraries versions are being update? (comming from Maven and Gradle world) so not sure how eclipse plugins manage dependencies (thanks in advance in case you can provide more info about this).

And..
I found some files: https://github.com/payara/ecosystem-eclipse-plugin/tree/master/releng/corundum-src/resources so wondering if latest eclipse platform versions has support for JNA on M1 chips from repos.

**Comment by JamesHillyard** [comment]
Hi @gdiazs,

My apologies for the long silence on this, internally we have been evaluating how we are going to fix this, we have also encountered other issues within the Eclipse plugin which we wish to resolve. This has ultimately lead us to the decision we will rewrite and modernise the Eclipse IDE plugin, I have noted internally that an aim of this rework will also include Apple M1 compatibility.

There currently is no ETA for this improvement, but we will address this in the future.

Best Regards,
James
