### ISSUE TITLE
Error creating a new proyect with eclipse wizzard and Payara Plugin / FISH-7546 

### ISSUE THREAD

**Issue by mcrose** [payara/ecosystem-support#72]
### Brief Summary

following the tutorial from [Payara Micro Tools in Eclipse IDE](https://docs.payara.fish/community/docs/Technical%20Documentation/Ecosystem/IDE%20Integration/Eclipse%20Plugin/Payara%20Micro.html)

I got errors on creation

```
Eclipse Version: 2023-06 (4.28.0)
Build id: 20230608-1333
Payara Micro Tools: 2.1.0
Payara Server Tools: 2.1.0
```

### Expected Outcome

project created

### Current Outcome

creating a new proyect 
**message:** An internal error occurred during: "Creating payara-micro-maven-archetype".

**Stack Trace:**
`java.lang.NoSuchMethodError: 'java.util.Collection org.eclipse.m2e.core.ui.internal.archetype.ArchetypeGenerator.createArchetypeProjects(org.eclipse.core.runtime.IPath, org.eclipse.m2e.core.project.IArchetype, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.util.Properties, org.eclipse.core.runtime.IProgressMonitor)'
	at fish.payara.eclipse.tools.micro.ui.wizards.MicroProjectWizard$1.doCreateMavenProjects(MicroProjectWizard.java:174)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectJob$1.doCreateMavenProjects(AbstractCreateMavenProjectJob.java:51)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:56)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectJob.runInWorkspace(AbstractCreateMavenProjectJob.java:55)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

### Reproducer

none

### Operating System

Windows 11 PRO

### JDK Version

Eclipse Temurin™ jdk-17.0.7+7

### Ecosystem Tool

Eclipse IDE Plugin

**Comment by mcrose** [comment]
also tried with
```
Eclipse Version: 2023-03 (4.27.0) Build id: 20230309-1520
Eclipse Temurin™ jdk-17.0.5+8

```

**Comment by Elifzeynepedman** [comment]
Hi @mcrose, 

I have been able to reproduce this issue and I have escalated this to the platform development team as `FISH-7546`.

Best Regards,
Elif
