### ISSUE TITLE
org.jdom.input.JDOMParseException: Error on line 1: Content ist nicht zulässig in Prolog.

### ISSUE THREAD

**Issue by StevenHachel** [payara/ecosystem-support#78]
### Brief Summary

Payara Platform Tools 1.6.0 defect

### Expected Outcome

org.jdom.input.JDOMParseException: Error on line 1: Content ist nicht zulässig in Prolog.
	at org.jdom.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:191)
	at org.jdom.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:212)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:586)
	at com.intellij.util.JdomKt.loadDocumentAndKeepBoundaryWhitespace(jdom.kt:66)
	at com.intellij.javaee.util.JavaeeJdomUtil.loadDocument(JavaeeJdomUtil.java:21)
	at com.intellij.javaee.util.JavaeeJdomUtil.loadDocument(JavaeeJdomUtil.java:16)
	at fish.payara.server.config.PayaraDomainConfigProcessor.getServerConfig(PayaraDomainConfigProcessor.java:85)
	at fish.payara.server.config.PayaraDomainConfigProcessor.getJavaConfig(PayaraDomainConfigProcessor.java:156)
	at fish.payara.server.config.PayaraDebugConfig.update(PayaraDebugConfig.java:78)
	at fish.payara.server.config.PayaraDebugConfig.update(PayaraDebugConfig.java:38)
	at com.intellij.javaee.oss.util.CachedConfig.check(CachedConfig.java:48)
	at com.intellij.javaee.oss.util.CachedConfig.get(CachedConfig.java:28)
	at fish.payara.server.config.PayaraConfig.access$000(PayaraConfig.java:26)
	at fish.payara.server.config.PayaraConfig$PayaraConfigFactory.get(PayaraConfig.java:55)
	at fish.payara.server.config.PayaraDebugConfig.getPort(PayaraDebugConfig.java:96)
	at fish.payara.server.PayaraStartupPolicy.initSettings(PayaraStartupPolicy.java:84)
	at fish.payara.server.PayaraStartupPolicy.initSettings(PayaraStartupPolicy.java:32)
	at com.intellij.javaee.oss.server.JavaeeStartupPolicy$1.initRunnerSettings(JavaeeStartupPolicy.java:53)
	at com.intellij.javaee.appServers.run.localRun.ScriptInfo.initRunnerSettings(ScriptInfo.java:46)
	at com.intellij.javaee.appServers.run.configuration.RunnerSpecificLocalConfigurationBit.readExternal(RunnerSpecificLocalConfigurationBit.java:140)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl$RunnerItem.add(RunnerAndConfigurationSettingsImpl.kt:572)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl$RunnerItem.loadState(RunnerAndConfigurationSettingsImpl.kt:509)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:250)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:64)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:46)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:63)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:182)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:239)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:236)
	at com.intellij.configurationStore.SchemeManagerIprProvider$processChildren$1.invoke(SchemeManagerIprProvider.kt:45)
	at com.intellij.configurationStore.SchemeManagerIprProvider$processChildren$1.invoke(SchemeManagerIprProvider.kt:43)
	at com.intellij.configurationStore.SchemeManagerIprProviderKt.read(SchemeManagerIprProvider.kt:140)
	at com.intellij.configurationStore.SchemeManagerIprProviderKt.access$read(SchemeManagerIprProvider.kt:1)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:43)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:236)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:298)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:867)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:87)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:488)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:415)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:121)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:577)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsyncIfDefined(ComponentManagerImpl.kt:646)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:637)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$execute$2.invokeSuspend(ProjectRunConfigurationInitializer.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:978)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.jdom.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:173)
	... 64 more

### Current Outcome

by starting IntelliJ 2023.2.4

### Reproducer

by starting IntelliJ 2023.2.4

### Operating System

Windows 10 Pro

### JDK Version

Eclipse Foundation\jdk-11.0.13.8-hotspot

### Ecosystem Tool

IntelliJ IDEA IDE Plugin

**Comment by shub8968** [comment]
Hi @StevenHachel ,

I'm unable to reproduce it. The plugin is working fine.
