### ISSUE TITLE
Intellij IDEA Plugin "Payara Ultimate Tools" no longer works with latest IDE version 2024.3 /FISH-9467

### ISSUE THREAD

**Issue by gako** [payara/ecosystem-support#92]
### Brief Summary

The Plugin "Payara Ultimate Tools" (1.10.0) only works for IDE version up to 241.*

### Expected Outcome

Plugin should support latest released version of intellij IDE

### Current Outcome

Plugin is listed as not supported in IDE Plugin Manager

### Reproducer

Goto Plugins in IDEA and try to install "Payara Ultimate Tools" Plugin with latest IDE version 242.*

### Operating System

Windows 11

### JDK Version

Zulu 21

### Ecosystem Tool

IntelliJ IDEA IDE Plugin

**Comment by felixif** [comment]
Hello @gako,

Thank you for your report. We just released a new version for the plugin, so everything should work fine now. For completeness, the internal issue was named `FISH-9467`, and was completed today. Please let me know if you encounter any issues.

Best regards,
Felix Ifrim

**Comment by eduarddrenth** [comment]
I still get:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'fish.payara.micro.actions.MigrateToJakartaEE10Action' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: fish.payara.intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by gako** [comment]
Hello, the same issue arise again with next idea version 2024.3, I updated the header accordingly.
